### PR TITLE
feat: minor field change for themes

### PR DESCRIPTION
**Pull request by UnbearableBear**
Linked to this issue in cdtn repo https://github.com/SocialGouv/code-du-travail-numerique/issues/2543 (description is basic text, no markdown)

(and subTitle is not used anywhere, nor fetched in datafiller data repo)

### CODE REVIEW

**Review by revolunet — APPROVED** [review]

**Comment by lionelB** [comment]
il vaut mieux éviter de commit les data

**Comment by revolunet** [comment]
je deploie ca ?

**Comment by lionelB** [comment]
> il vaut mieux éviter de commit les data

je me suis quiché de PR :D

**Comment by lionelB** [comment]
go deploy !

**Pull request merged**
